spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:batchdb'
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false

application:
  batch:
    input-path: d:/Application/spring-batch/src/main/resources